# Generated by Django 4.2.16 on 2024-10-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('task', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=100)),
                ('state', models.BooleanField()),
            ],
        ),
    ]
