# Generated by Django 4.2.16 on 2024-10-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItems',
            new_name='TodoItem',
        ),
        migrations.RemoveField(
            model_name='todogroup',
            name='state',
        ),
    ]
